# Generated by Django 4.2.28 on 2026-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_add_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='callsign',
            field=models.CharField(blank=True, max_length=50, verbose_name='Позивний'),
        ),
    ]
