# Generated by Django 4.2.28 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_add_callsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Формат: +380000000000. Використовується для верифікації бота.', max_length=20, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
