# Generated by Django 4.2.28 on 2026-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
    ]
