# Generated by Django 6.0 on 2026-01-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('propulsion', models.CharField(blank=True, max_length=150)),
                ('max_speed_kmh', models.PositiveIntegerField(blank=True, null=True)),
                ('max_range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('endurance_min', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DroneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=150)),
                ('payload', models.CharField(blank=True, max_length=200)),
                ('avionics', models.CharField(blank=True, max_length=200)),
                ('power_system', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='wiki.drone')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ConfigurationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='wiki.droneconfiguration')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('configuration', 'name')},
            },
        ),
    ]
