# Generated by Django 6.0 on 2026-01-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional short label (emoji/text) for quick scanning.', max_length=60)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='droneconfiguration',
            name='drone',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Single paragraph overview used in listings.')),
                ('tags', models.CharField(blank=True, help_text='Comma separated keywords for search and quick filtering.', max_length=200)),
                ('body', models.TextField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('references', models.TextField(blank=True, help_text='One reference per line (e.g. URLs, manuals).')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='wiki.topic')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.DeleteModel(
            name='ConfigurationParameter',
        ),
        migrations.DeleteModel(
            name='Drone',
        ),
        migrations.DeleteModel(
            name='DroneConfiguration',
        ),
    ]
