# Generated by Django 4.2.28 on 2026-02-11 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expense_log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('description', models.CharField(max_length=300, verbose_name='На що витрачено')),
                ('receipt', models.FileField(blank=True, help_text='Фото або документ квитанції.', upload_to=expense_log.models.expense_receipt_path, verbose_name='Квитанція')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Витрата',
                'verbose_name_plural': 'Витрати',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
