# Generated by Django 4.2.28 on 2026-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='На що витрачено'),
        ),
    ]
