# Generated by Django 4.2.28 on 2026-02-11 15:31

from django.db import migrations, models
import expense_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0003_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, help_text='Фото або документ квитанції.', max_length=500, upload_to=expense_log.models.expense_receipt_path, verbose_name='Квитанція'),
        ),
    ]
