"""
Django settings for app_drones project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


def str_to_bool(value):
    """Convert string to boolean."""
    if isinstance(value, bool):
        return value
    if value.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif value.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise ValueError(f'Cannot convert {value} to boolean')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-70kwntf%p2*59yc7b&2^5h^m@(&9b&j&d9ygr&f(z$#tw5o65*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.getenv('DEBUG', 'True'))


ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", default="*").split(",")
if DEBUG:
    default_csrf_origins = "http://127.0.0.1:8000,http://localhost:8000"
else:
    default_csrf_origins = None

csrf_origins_str = os.getenv("CSRF_TRUSTED_ORIGINS", default=default_csrf_origins)
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = csrf_origins_str.split(",")
else:
    CSRF_TRUSTED_ORIGINS = []



# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'wiki',
    'documentation',
    'equipment_accounting',
    'expense_log',
    'user_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app_drones.middleware.superuser_required_for_admin',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_drones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app_drones.context_processors.user_groups',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_drones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'app_drones.adapters.CustomAuthenticationBackend',
]

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'password1*', 'password2*']

ACCOUNT_ADAPTER = 'app_drones.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'app_drones.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_LOGIN_BY_CODE_ENABLED = True
SOCIALACCOUNT_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
    },
}


# ---------------------------------------------------------------------------
# Django Unfold
# ---------------------------------------------------------------------------

from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Майстерня",
    "SITE_HEADER": "Майстерня",
    "SITE_SYMBOL": "flight",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Користувачі",
                "separator": True,
                "items": [
                    {
                        "title": "Користувачі",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": "Wiki",
                "separator": True,
                "items": [
                    {
                        "title": "Теми",
                        "icon": "category",
                        "link": reverse_lazy("admin:wiki_topic_changelist"),
                    },
                    {
                        "title": "Статті",
                        "icon": "article",
                        "link": reverse_lazy("admin:wiki_article_changelist"),
                    },
                ],
            },
            {
                "title": "Документація",
                "separator": True,
                "items": [
                    {
                        "title": "Категорії",
                        "icon": "folder",
                        "link": reverse_lazy(
                            "admin:documentation_category_changelist"
                        ),
                    },
                    {
                        "title": "Сторінки",
                        "icon": "description",
                        "link": reverse_lazy(
                            "admin:documentation_page_changelist"
                        ),
                    },
                    {
                        "title": "Коментарі",
                        "icon": "comment",
                        "link": reverse_lazy(
                            "admin:documentation_comment_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Довідники",
                "separator": True,
                "items": [
                    {
                        "title": "Виробники",
                        "icon": "factory",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_manufacturer_changelist"
                        ),
                    },
                    {
                        "title": "Моделі дронів",
                        "icon": "drone",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_dronemodel_changelist"
                        ),
                    },
                    {
                        "title": "Призначення",
                        "icon": "target",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_dronepurpose_changelist"
                        ),
                    },
                    {
                        "title": "Частоти",
                        "icon": "wifi",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_frequency_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Шаблони сумісності",
                "separator": True,
                "items": [
                    {
                        "title": "Шаблони живлення",
                        "icon": "battery_charging_full",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_powertemplate_changelist"
                        ),
                    },
                    {
                        "title": "Шаблони відео",
                        "icon": "videocam",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_videotemplate_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Типи БПЛА",
                "separator": True,
                "items": [
                    {
                        "title": "FPV дрони",
                        "icon": "flight",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_fpvdronetype_changelist"
                        ),
                    },
                    {
                        "title": "Оптичні дрони",
                        "icon": "cable",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_opticaldronetype_changelist"
                        ),
                    },
                    {
                        "title": "БПЛА (екземпляри)",
                        "icon": "inventory",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_uavinstance_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Комплектуючі",
                "separator": True,
                "items": [
                    {
                        "title": "Типи батарей",
                        "icon": "battery_full",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_batterytype_changelist"
                        ),
                    },
                    {
                        "title": "Типи котушок",
                        "icon": "settings_input_svideo",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_spooltype_changelist"
                        ),
                    },
                    {
                        "title": "Інші комплектуючі",
                        "icon": "settings",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_othercomponenttype_changelist"
                        ),
                    },
                    {
                        "title": "Комплектуючі",
                        "icon": "memory",
                        "link": reverse_lazy(
                            "admin:equipment_accounting_component_changelist"
                        ),
                    },
                ],
            },
            {
                "title": "Фінанси",
                "separator": True,
                "items": [
                    {
                        "title": "Витрати",
                        "icon": "payments",
                        "link": reverse_lazy(
                            "admin:expense_log_expense_changelist"
                        ),
                    },
                ],
            },
        ],
    },
}
