# Generated by Django 4.2.28 on 2026-03-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_date', models.DateField(verbose_name='Дата удару')),
                ('target_description', models.CharField(max_length=300, verbose_name='Ціль')),
                ('result_description', models.TextField(verbose_name='Результат')),
                ('drone_used', models.CharField(blank=True, max_length=150, verbose_name='Дрон (опис)')),
                ('location_description', models.CharField(blank=True, max_length=300, verbose_name='Місце')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='strikes/%Y/%m/', verbose_name='Фото')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата звіту')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strike_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пілот')),
            ],
            options={
                'verbose_name': 'Звіт про удар',
                'verbose_name_plural': 'Звіти про удари',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'В роботі'), ('ready', 'Готово'), ('delivered', 'Видано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки пілота')),
                ('master_notes', models.TextField(blank=True, verbose_name='Примітки майстра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Замовлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Тип БПЛА (тип)')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_drone_orders', to=settings.AUTH_USER_MODEL, verbose_name='Обробляє')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пілот')),
            ],
            options={
                'verbose_name': 'Замовлення дрона',
                'verbose_name_plural': 'Замовлення дронів',
                'ordering': ['-created_at'],
            },
        ),
    ]
