# Generated by Django 4.2.28 on 2026-03-11 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_date', models.DateField(verbose_name='Дата')),
                ('crew', models.CharField(choices=[('АКУЛА', 'АКУЛА'), ('БОЦМАН', 'БОЦМАН'), ('ДЕМЕНТОР', 'ДЕМЕНТОР'), ('КАЙМАН', 'КАЙМАН'), ('КАЖАН', 'КАЖАН'), ('КОСМОНАВТ', 'КОСМОНАВТ'), ('КАПЕР', 'КАПЕР'), ('РАКЕТА', 'РАКЕТА'), ('ПУГАЧ', 'ПУГАЧ'), ('ЗЛЮКА', 'ЗЛЮКА'), ('СУЗУКІ', 'СУЗУКІ'), ('КРЕЧЕТ', 'КРЕЧЕТ'), ('АКВІЛА', 'АКВІЛА'), ('ДЕВЕРСАНТ', 'ДЕВЕРСАНТ'), ('АЛЬГІЗ', 'АЛЬГІЗ'), ('ПЕКАРЬ', 'ПЕКАРЬ'), ('ПАЛІЙ', 'ПАЛІЙ'), ('АМІГО', 'АМІГО'), ('ФАРАДЕЙ', 'ФАРАДЕЙ'), ('ГРИФ', 'ГРИФ'), ('ХАНТЕР', 'ХАНТЕР'), ('СКАУТ', 'СКАУТ'), ('СТУДЕНТ', 'СТУДЕНТ'), ('ГАРПІЯ', 'ГАРПІЯ'), ('ЛЮТИЙ', 'ЛЮТИЙ'), ('ХАРОН', 'ХАРОН'), ('Мікі', 'Мікі'), ('Амулет', 'Амулет'), ('ШЕРШЕНЬ', 'ШЕРШЕНЬ'), ('ВОРОН', 'ВОРОН'), ('КРОТ', 'КРОТ')], max_length=50, verbose_name='Екіпаж')),
                ('weapon_type', models.CharField(choices=[('FPV', 'FPV'), ('FPV ОПТОВОЛОКНО', 'FPV ОПТОВОЛОКНО'), ('FPV БОМБЕР', 'FPV БОМБЕР'), ('VAMPIRE', 'VAMPIRE'), ('MAVIC', 'MAVIC'), ('MATRICE', 'MATRICE'), ('КАЖАН', 'КАЖАН'), ('HEAVY SHOT', 'HEAVY SHOT'), ('NEMESIS', 'NEMESIS'), ('AVENGER', 'AVENGER'), ('Перун', 'Перун'), ('Батон 13', 'Батон 13'), ('Шершень', 'Шершень')], max_length=50, verbose_name='Засіб')),
                ('weapon_name', models.CharField(choices=[('SHRIKE 7', 'SHRIKE 7'), ('SHRIKE 10', 'SHRIKE 10'), ('SHRIKE 10T', 'SHRIKE 10T'), ('MAMONTH 10', 'MAMONTH 10'), ('MAMONTH 13', 'MAMONTH 13'), ('MAMONTH 10T', 'MAMONTH 10T'), ('F7', 'F7'), ('F10', 'F10'), ('F10T', 'F10T'), ('KOLIBRI 7', 'KOLIBRI 7'), ('KOLIBRI 8', 'KOLIBRI 8'), ('KOLIBRI 10', 'KOLIBRI 10'), ('KOLIBRI 10T', 'KOLIBRI 10T'), ('SPARROW 2', 'SPARROW 2'), ('SPARROW 2T', 'SPARROW 2T'), ('RUSORIZ 8', 'RUSORIZ 8'), ('RUSORIZ 10', 'RUSORIZ 10'), ('PEGAS 7', 'PEGAS 7'), ('PEGAS 7T', 'PEGAS 7T'), ('MOSKAL HUNTER', 'MOSKAL HUNTER'), ('GENERAL CHERESHNYA', 'GENERAL CHERESHNYA'), ('GENERAL CHERESHNYA THERMAL', 'GENERAL CHERESHNYA THERMAL'), ('DYKIY SHERHEN', 'DYKIY SHERHEN'), ('RIY POMSTY', 'RIY POMSTY'), ('VYRIY 10', 'VYRIY 10'), ('VYRIY 10T', 'VYRIY 10T'), ('VYRIY 10 OPTIC', 'VYRIY 10 OPTIC'), ('OPTORIZ', 'OPTORIZ'), ('OPTORIZ 13', 'OPTORIZ 13'), ('STALKER 10', 'STALKER 10'), ('STALKER 15', 'STALKER 15'), ('SPOOK 8', 'SPOOK 8'), ('SPOOK 10', 'SPOOK 10'), ('SPOOK 8T', 'SPOOK 8T'), ('SPOOK 10T', 'SPOOK 10T'), ('MOLFAR', 'MOLFAR'), ('ENTERPRICE 10', 'ENTERPRICE 10'), ('ENTERPRICE 10T', 'ENTERPRICE 10T'), ('ENTERPRICE 15', 'ENTERPRICE 15'), ('ENTERPRICE 13', 'ENTERPRICE 13'), ('BLINK 8', 'BLINK 8'), ('BLINK 10', 'BLINK 10'), ('TIN', 'TIN'), ('CHAYKA 10', 'CHAYKA 10'), ('CHAYKA 13', 'CHAYKA 13'), ('GRIM', 'GRIM'), ('HUNTER 10', 'HUNTER 10'), ('HUNTER 15', 'HUNTER 15'), ('SKYRIPER', 'SKYRIPER'), ('BATON', 'BATON'), ('GARPIYA', 'GARPIYA'), ('SAPSAN', 'SAPSAN'), ('MAVIC 3', 'MAVIC 3'), ('MAVIC 3 PRO', 'MAVIC 3 PRO'), ('MAVIC 3T', 'MAVIC 3T'), ('MAVIC 3E', 'MAVIC 3E'), ('AUTEL EVO MAX 4T', 'AUTEL EVO MAX 4T'), ('AUTEL EVO MAX 4N', 'AUTEL EVO MAX 4N'), ('MATRICE 4E', 'MATRICE 4E'), ('MATRICE 4T', 'MATRICE 4T'), ('VAMPIRE GEN 2', 'VAMPIRE GEN 2'), ('KAZHAN', 'KAZHAN'), ('MAD CAT  13', 'MAD CAT  13'), ('SWITLOWOD', 'SWITLOWOD'), ('KOLIBRI 7 ЖДУН', 'KOLIBRI 7 ЖДУН'), ('SHRIKE 10 ЖДУН', 'SHRIKE 10 ЖДУН'), ('BOMBUS 10', 'BOMBUS 10'), ('BOMBUS 10T', 'BOMBUS 10T'), ('BOMBUS 15', 'BOMBUS 15'), ('BOMBUS 15T', 'BOMBUS 15T'), ('SEAGULL 13', 'SEAGULL 13'), ('ГОРИНЬ 13', 'ГОРИНЬ 13'), ('ГОРИНЬ 13Т', 'ГОРИНЬ 13Т'), ('SPALAKH 10', 'SPALAKH 10'), ('А 10', 'А 10'), ('Гріф 10', 'Гріф 10'), ('VIPER', 'VIPER'), ('NEMESIS', 'NEMESIS'), ('SHURIKEN 10', 'SHURIKEN 10'), ('SHURIKEN 10 T', 'SHURIKEN 10 T'), ('AVENGER', 'AVENGER'), ('ПЕРУН', 'ПЕРУН'), ('BATON 13', 'BATON 13'), ('БАХМУТ 10', 'БАХМУТ 10'), ('ГОРОБЕЦЬ 13 ОВ', 'ГОРОБЕЦЬ 13 ОВ'), ('BESHKET 10', 'BESHKET 10'), ('BESHKET 10 T', 'BESHKET 10 T')], max_length=100, verbose_name='Назва засобу')),
                ('ammo_type', models.CharField(choices=[('АО-1', 'АО-1'), ('АО-2.5', 'АО-2.5'), ('АО-2.5х2', 'АО-2.5х2'), ('БНПП 40', 'БНПП 40'), ('ВОГ-17', 'ВОГ-17'), ('ВОГ-25', 'ВОГ-25'), ('ГРАНАТА-ЗАПАЛЬНИЧКА', 'ГРАНАТА-ЗАПАЛЬНИЧКА'), ('ЗАБ', 'ЗАБ'), ('КЗ-6', 'КЗ-6'), ('ПГ-7', 'ПГ-7'), ('ПГ-9', 'ПГ-9'), ('ТАБ К1.4', 'ТАБ К1.4'), ('ТЕРМІТ 500', 'ТЕРМІТ 500'), ('ТЕРМІТ 100', 'ТЕРМІТ 100'), ('ТМ', 'ТМ'), ('У250', 'У250'), ('УФ1500', 'УФ1500'), ('Ф1000', 'Ф1000'), ('Ф1300', 'Ф1300'), ('Ф 1600', 'Ф 1600'), ('Ф2000', 'Ф2000'), ('Ф3000', 'Ф3000'), ('МОА1200', 'МОА1200'), ('МОА4900', 'МОА4900'), ('МОА9000', 'МОА9000'), ('НАПАЛМ', 'НАПАЛМ'), ('РКГ', 'РКГ'), ('ПОМ-2', 'ПОМ-2'), ('ПФМ 1', 'ПФМ 1'), ('ПТМ', 'ПТМ'), ('ПТМ 2,4', 'ПТМ 2,4'), ('ПТМ3М', 'ПТМ3М'), ('Ф-1', 'Ф-1'), ('М82', 'М82'), ('Т2000', 'Т2000'), ('Т4000', 'Т4000'), ('МК 1500 ТЮЛЬПАН', 'МК 1500 ТЮЛЬПАН'), ('АЕРОЗОЛЬ АКТИВОВАНИЙ', 'АЕРОЗОЛЬ АКТИВОВАНИЙ'), ('ВОДА АКТИВОВАНА', 'ВОДА АКТИВОВАНА'), ('ДИМ АКТИВОВАНИЙ', 'ДИМ АКТИВОВАНИЙ'), ('КОНЬЯК АКТИВОВАНИЙ', 'КОНЬЯК АКТИВОВАНИЙ'), ('ПОСИЛКА', 'ПОСИЛКА'), ('КУ 900', 'КУ 900'), ('КУ 1500', 'КУ 1500'), ('ЧІКУШКА', 'ЧІКУШКА'), ('РОСА', 'РОСА'), ('ВАЛДАС', 'ВАЛДАС'), ('Т1000', 'Т1000'), ('ТЕРМІТ 1800', 'ТЕРМІТ 1800'), ('Міна 60мм', 'Міна 60мм'), ('Артріт', 'Артріт'), ('ФАБ 8.5', 'ФАБ 8.5'), ('ФАБ 4.5', 'ФАБ 4.5'), ('ОГ-9', 'ОГ-9'), ('УБ-65', 'УБ-65'), ('БРЕВНО', 'БРЕВНО'), ('ТБ1800', 'ТБ1800'), ('ОГБ-1', 'ОГБ-1'), ('УФ-2000 "ГОРОХ"', 'УФ-2000 "ГОРОХ"'), ('AVG-4000', 'AVG-4000'), ('Міна 120', 'Міна 120'), ('ІБМ-1', 'ІБМ-1'), ('МІна Сир', 'МІна Сир'), ('У1000', 'У1000'), ('F27', 'F27')], max_length=100, verbose_name='БК')),
                ('initiation_type', models.CharField(choices=[('УЗРГМ', 'УЗРГМ'), ('УДЗ', 'УДЗ'), ('УДЗ НА УДАР', 'УДЗ НА УДАР'), ('МУВ', 'МУВ'), ('ЕЛЕКТРОДЕТОНАТОР', 'ЕЛЕКТРОДЕТОНАТОР'), ('НАКОЛ', 'НАКОЛ'), ('3D ЗАМИКАЧ', '3D ЗАМИКАЧ'), ('ДЖОНІК', 'ДЖОНІК'), ('РОЗТЯЖКА', 'РОЗТЯЖКА'), ('Запезпечення', 'Запезпечення')], max_length=50, verbose_name='Ініціація')),
                ('target_type', models.CharField(choices=[('КУЩ', 'КУЩ'), ('АТ', 'АТ'), ('ВАТ', 'ВАТ'), ('БТ', 'БТ'), ('МІНОМЕТ', 'МІНОМЕТ'), ('ГАРМАТА', 'ГАРМАТА'), ('ІФС', 'ІФС'), ('ПІХОТА', 'ПІХОТА'), ('РЕБ', 'РЕБ'), ('АНТЕНА', 'АНТЕНА'), ('МАЙНО', 'МАЙНО'), ('ПММ', 'ПММ'), ('МОТОЦИКЛ', 'МОТОЦИКЛ'), ('КВАДРОЦИКЛ', 'КВАДРОЦИКЛ'), ('БК', 'БК'), ('ЖДУН', 'ЖДУН'), ('ДОРОГА', 'ДОРОГА'), ('БПЛА', 'БПЛА'), ('НРК', 'НРК'), ('ЗУ', 'ЗУ'), ('РЛС', 'РЛС'), ('ІНШЕ', 'ІНШЕ'), ('Посилка', 'Посилка'), ('Посадка', 'Посадка')], max_length=50, verbose_name='Ціль')),
                ('result_type', models.CharField(choices=[('200', '200'), ('300', '300'), ('Р-Н ЦІЛІ', 'Р-Н ЦІЛІ'), ('НЕРОЗРИВ', 'НЕРОЗРИВ'), ('НЕДОЛІТ', 'НЕДОЛІТ'), ('ОБРИВ ВОЛОКНА', 'ОБРИВ ВОЛОКНА'), ('ДІЯ РЕБ', 'ДІЯ РЕБ'), ('ЗБИЛИ ЗІ СТРІЛЕЦЬКОЇ ЗБРОЇ', 'ЗБИЛИ ЗІ СТРІЛЕЦЬКОЇ ЗБРОЇ'), ('МІНУВАННЯ', 'МІНУВАННЯ'), ('ВТРАТА КЕРУВАННЯ', 'ВТРАТА КЕРУВАННЯ'), ('ВТРАТА ЗВЯЗКУ', 'ВТРАТА ЗВЯЗКУ'), ('ЗГОРІВ VTX', 'ЗГОРІВ VTX'), ('ДЕФЕКТ ДРОНА', 'ДЕФЕКТ ДРОНА'), ('Закінчилось волокно', 'Закінчилось волокно')], max_length=100, verbose_name='Результат')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата звіту')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strike_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пілот')),
            ],
            options={
                'verbose_name': 'Звіт про удар',
                'verbose_name_plural': 'Звіти про удари',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'В роботі'), ('ready', 'Готово'), ('delivered', 'Видано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки пілота')),
                ('master_notes', models.TextField(blank=True, verbose_name='Примітки майстра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Замовлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Тип БПЛА (тип)')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_drone_orders', to=settings.AUTH_USER_MODEL, verbose_name='Обробляє')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пілот')),
            ],
            options={
                'verbose_name': 'Замовлення дрона',
                'verbose_name_plural': 'Замовлення дронів',
                'ordering': ['-created_at'],
            },
        ),
    ]
