# Generated by Django 4.2.28 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strikereport',
            name='video',
            field=models.FileField(blank=True, help_text='Файл відео результату удару (MP4, MOV тощо)', null=True, upload_to='strikes/videos/%Y/%m/', verbose_name='Відео'),
        ),
    ]
