# Generated by Django 4.2.28 on 2026-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('file', models.FileField(upload_to='knowledge_docs/', verbose_name='Файл')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Розмір (байт)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сторінок')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Витягнутий текст')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('processing', 'Обробляється'), ('ready', 'Готово'), ('error', 'Помилка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Документ бази знань',
                'verbose_name_plural': 'Документи бази знань',
                'ordering': ('-created_at',),
            },
        ),
    ]
