# Generated by Django 4.2.28 on 2026-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_msg_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('raw_text', models.TextField(verbose_name='Сирий текст')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Відправник')),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='Група')),
                ('received_at', models.DateTimeField(verbose_name='Час отримання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pozyvnyi', models.CharField(blank=True, max_length=100, verbose_name='Поз')),
                ('crew', models.CharField(blank=True, max_length=100, verbose_name='ЕК')),
                ('zasib', models.CharField(blank=True, max_length=200, verbose_name='Засіб')),
                ('bk', models.CharField(blank=True, max_length=200, verbose_name='БК')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='Ціль')),
                ('coordinates', models.CharField(blank=True, max_length=100, verbose_name='Координати')),
                ('result', models.CharField(blank=True, choices=[('destroyed', 'Знищено'), ('damaged', 'Пошкоджено'), ('missed', 'Не вражено'), ('unknown', 'Невідомо')], max_length=20, verbose_name='Результат')),
                ('parsed_ok', models.BooleanField(default=False, verbose_name='Розпізнано')),
            ],
            options={
                'verbose_name': 'Звіт ураження',
                'verbose_name_plural': 'Звіти уражень',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='whatsapp_mo_receive_ecbc28_idx'), models.Index(fields=['result'], name='whatsapp_mo_result_ff8c74_idx'), models.Index(fields=['pozyvnyi'], name='whatsapp_mo_pozyvny_446617_idx')],
            },
        ),
    ]
