# Generated by Django 4.2.28 on 2026-02-11 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('charging', 'Charging'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_charge_cycles', models.IntegerField(blank=True, default=0, null=True)),
                ('health_percentage', models.IntegerField(blank=True, default=100, null=True)),
                ('last_charge_date', models.DateField(blank=True, null=True)),
                ('remaining_fiber_length', models.FloatField(blank=True, help_text='Meters', null=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Component category',
                'verbose_name_plural': 'Component categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged'), ('repair', 'In repair'), ('retired', 'Retired')], default='operational', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('total_flight_hours', models.FloatField(default=0)),
                ('total_flights', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drone category',
                'verbose_name_plural': 'Drone categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('repair', 'Repair'), ('upgrade', 'Upgrade'), ('inspection', 'Inspection'), ('calibration', 'Calibration')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment_accounting.component')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment_accounting.drone')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance record',
                'verbose_name_plural': 'Maintenance records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('mission_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('weather_conditions', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('max_altitude', models.FloatField(blank=True, help_text='Meters', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batteries_used', models.ManyToManyField(blank=True, related_name='flight_logs', to='equipment_accounting.component')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='equipment_accounting.drone')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight log',
                'verbose_name_plural': 'Flight logs',
                'ordering': ['-flight_date'],
            },
        ),
        migrations.CreateModel(
            name='DroneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('has_thermal_camera', models.BooleanField(default=False)),
                ('is_night_capable', models.BooleanField(default=False)),
                ('has_optical_fiber', models.BooleanField(default=False)),
                ('max_flight_time', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('max_range', models.IntegerField(blank=True, help_text='Meters', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('max_payload', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_types', to='equipment_accounting.dronecategory')),
            ],
            options={
                'verbose_name': 'Drone type',
                'verbose_name_plural': 'Drone types',
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drones', to='equipment_accounting.dronetype'),
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_types', to='equipment_accounting.componentcategory')),
                ('compatible_drone_types', models.ManyToManyField(blank=True, related_name='compatible_components', to='equipment_accounting.dronetype')),
            ],
            options={
                'verbose_name': 'Component type',
                'verbose_name_plural': 'Component types',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'manufacturer', 'model')},
            },
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to_drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='equipment_accounting.drone'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='equipment_accounting.componenttype'),
        ),
    ]
