# Generated by Django 4.2.28 on 2026-02-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Модель дрона',
                'verbose_name_plural': 'Моделі дронів',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DronePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Призначення дрона',
                'verbose_name_plural': 'Призначення дронів',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значення')),
                ('unit', models.CharField(choices=[('mhz', 'MHz'), ('ghz', 'GHz')], max_length=10, verbose_name='Одиниця')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Частота',
                'verbose_name_plural': 'Частоти',
                'ordering': ['value'],
                'unique_together': {('value', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.CharField(choices=[('controller', 'Пульт'), ('charger', 'Зарядка'), ('propeller', 'Пропелер'), ('other', 'Інше')], max_length=20, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Інша комплектуюча',
                'verbose_name_plural': 'Інші комплектуючі',
            },
        ),
        migrations.CreateModel(
            name='PowerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('connector', models.CharField(choices=[('xt30', 'XT30'), ('xt60', 'XT60'), ('xt90', 'XT90'), ('deans', 'Deans'), ('ec5', 'EC5')], max_length=20, verbose_name='Тип конектора')),
                ('configuration', models.CharField(choices=[('3s1p', '3S1P'), ('3s2p', '3S2P'), ('3s3p', '3S3P'), ('4s1p', '4S1P'), ('4s2p', '4S2P'), ('4s3p', '4S3P'), ('4s4p', '4S4P'), ('6s1p', '6S1P'), ('6s2p', '6S2P'), ('6s3p', '6S3P')], max_length=10, verbose_name='Конфігурація')),
                ('capacity', models.IntegerField(verbose_name='Ємність (mAh)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Шаблон живлення',
                'verbose_name_plural': 'Шаблони живлення',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('is_analog', models.BooleanField(default=True, verbose_name='Аналоговий сигнал')),
                ('max_distance', models.IntegerField(verbose_name='Дальність польоту (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Шаблон відео',
                'verbose_name_plural': 'Шаблони відео',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UAVInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серійний номер')),
                ('status', models.CharField(choices=[('operational', 'Працює'), ('maintenance', 'На обслуговуванні'), ('damaged', 'Пошкоджений'), ('retired', 'Списаний'), ('destroyed', 'Знищений')], default='operational', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Тип БПЛА')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uavs', to=settings.AUTH_USER_MODEL, verbose_name='Додав')),
            ],
            options={
                'verbose_name': 'БПЛА (екземпляр)',
                'verbose_name_plural': 'БПЛА (екземпляри)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('video_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.videotemplate', verbose_name='Шаблон відео')),
            ],
            options={
                'verbose_name': 'Тип котушки',
                'verbose_name_plural': 'Типи котушок',
            },
        ),
        migrations.CreateModel(
            name='OpticalDroneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_size', models.CharField(choices=[('7', '7"'), ('8', '8"'), ('10', '10"'), ('11', '11"'), ('13', '13"'), ('15', '15"'), ('16', '16"')], max_length=3, verbose_name='Розмір пропелерів')),
                ('has_thermal', models.BooleanField(default=False, verbose_name='Термальна камера')),
                ('is_unusable', models.BooleanField(default=False, verbose_name='Не може використовуватися')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('control_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_control', to='equipment_accounting.frequency', verbose_name='Частота керування')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronemodel', verbose_name='Модель')),
                ('power_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.powertemplate', verbose_name='Шаблон живлення')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronepurpose', verbose_name='Призначення')),
                ('video_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.videotemplate', verbose_name='Шаблон відео')),
            ],
            options={
                'verbose_name': 'Тип оптичного дрона',
                'verbose_name_plural': 'Типи оптичних дронів',
            },
        ),
        migrations.CreateModel(
            name='FPVDroneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_size', models.CharField(choices=[('7', '7"'), ('8', '8"'), ('10', '10"'), ('11', '11"'), ('13', '13"'), ('15', '15"'), ('16', '16"')], max_length=3, verbose_name='Розмір пропелерів')),
                ('has_thermal', models.BooleanField(default=False, verbose_name='Термальна камера')),
                ('is_unusable', models.BooleanField(default=False, verbose_name='Не може використовуватися')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('control_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_control', to='equipment_accounting.frequency', verbose_name='Частота керування')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronemodel', verbose_name='Модель')),
                ('power_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.powertemplate', verbose_name='Шаблон живлення')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronepurpose', verbose_name='Призначення')),
                ('video_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fpv_video', to='equipment_accounting.frequency', verbose_name='Частота відео')),
            ],
            options={
                'verbose_name': 'Тип FPV дрона',
                'verbose_name_plural': 'Типи FPV дронів',
            },
        ),
        migrations.AddField(
            model_name='dronemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_models', to='equipment_accounting.manufacturer', verbose_name='Виробник'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('in_use', 'Використовується'), ('damaged', 'Пошкоджена'), ('retired', 'Списана')], default='available', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assigned_to_uav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='equipment_accounting.uavinstance', verbose_name='Закріплена за БПЛА')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Тип комплектуючої')),
            ],
            options={
                'verbose_name': 'Комплектуюча',
                'verbose_name_plural': 'Комплектуючі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('power_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.powertemplate', verbose_name='Шаблон живлення')),
            ],
            options={
                'verbose_name': 'Тип батареї',
                'verbose_name_plural': 'Типи батарей',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dronemodel',
            unique_together={('manufacturer', 'name')},
        ),
    ]
