# Generated by Django 4.2.28 on 2026-02-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uavinstance',
            name='serial_number',
        ),
    ]
