# Generated by Django 4.2.28 on 2026-02-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комплектуюча', 'verbose_name_plural': 'Комплектуючі'},
        ),
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категорія комплектуючої', 'verbose_name_plural': 'Категорії комплектуючих'},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Тип комплектуючої', 'verbose_name_plural': 'Типи комплектуючих'},
        ),
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дрон', 'verbose_name_plural': 'Дрони'},
        ),
        migrations.AlterModelOptions(
            name='dronecategory',
            options={'ordering': ['name'], 'verbose_name': 'Категорія дрона', 'verbose_name_plural': 'Категорії дронів'},
        ),
        migrations.AlterModelOptions(
            name='dronetype',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Тип дрона', 'verbose_name_plural': 'Типи дронів'},
        ),
        migrations.AlterModelOptions(
            name='flightlog',
            options={'ordering': ['-flight_date'], 'verbose_name': 'Запис про політ', 'verbose_name_plural': 'Журнал польотів'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-date'], 'verbose_name': 'Запис про обслуговування', 'verbose_name_plural': 'Журнал обслуговування'},
        ),
        migrations.AlterField(
            model_name='component',
            name='assigned_to_drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='equipment_accounting.drone', verbose_name='Закріплена за дроном'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='equipment_accounting.componenttype', verbose_name='Тип комплектуючої'),
        ),
        migrations.AlterField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='component',
            name='current_charge_cycles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Поточна кількість циклів заряду'),
        ),
        migrations.AlterField(
            model_name='component',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поточна локація'),
        ),
        migrations.AlterField(
            model_name='component',
            name='health_percentage',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name="Здоров'я батареї (%)"),
        ),
        migrations.AlterField(
            model_name='component',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AlterField(
            model_name='component',
            name='last_charge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Остання зарядка'),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='component',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата придбання'),
        ),
        migrations.AlterField(
            model_name='component',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна придбання'),
        ),
        migrations.AlterField(
            model_name='component',
            name='remaining_fiber_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Залишок оптоволокна (м)'),
        ),
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('in_use', 'Використовується'), ('charging', 'На зарядці'), ('maintenance', 'На обслуговуванні'), ('damaged', 'Пошкоджена'), ('retired', 'Списана')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_types', to='equipment_accounting.componentcategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='compatible_drone_types',
            field=models.ManyToManyField(blank=True, related_name='compatible_components', to='equipment_accounting.dronetype', verbose_name='Сумісні типи дронів'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drones', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальна особа'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поточна локація'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drones', to='equipment_accounting.dronetype', verbose_name='Тип дрона'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата придбання'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна придбання'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.CharField(choices=[('operational', 'Працює'), ('maintenance', 'На обслуговуванні'), ('damaged', 'Пошкоджений'), ('repair', 'В ремонті'), ('retired', 'Списаний')], default='operational', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='total_flight_hours',
            field=models.FloatField(default=0, verbose_name='Загальний наліт (год)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='total_flights',
            field=models.IntegerField(default=0, verbose_name='Кількість польотів'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_types', to='equipment_accounting.dronecategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='has_optical_fiber',
            field=models.BooleanField(default=False, verbose_name='Оптоволокно'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='has_thermal_camera',
            field=models.BooleanField(default=False, verbose_name='Термальна камера'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='is_night_capable',
            field=models.BooleanField(default=False, verbose_name='Нічний режим'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='max_flight_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. час польоту (хв)'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='max_payload',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. корисне навантаження (г)'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='max_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. дальність (м)'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='max_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. швидкість (км/год)'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Технічні характеристики'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вага (г)'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='batteries_used',
            field=models.ManyToManyField(blank=True, related_name='flight_logs', to='equipment_accounting.component', verbose_name='Використані батареї'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Дистанція (км)'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='equipment_accounting.drone', verbose_name='Дрон'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='duration_minutes',
            field=models.IntegerField(verbose_name='Тривалість (хв)'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_date',
            field=models.DateTimeField(verbose_name='Дата і час польоту'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='max_altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. висота (м)'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='mission_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип місії'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to=settings.AUTH_USER_MODEL, verbose_name='Пілот'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=200, verbose_name='Погодні умови'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment_accounting.component', verbose_name='Комплектуюча'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment_accounting.drone', verbose_name='Дрон'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('scheduled', 'Планове ТО'), ('repair', 'Ремонт'), ('upgrade', 'Модернізація'), ('inspection', 'Огляд'), ('calibration', 'Калібрування')], max_length=20, verbose_name='Тип обслуговування'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Наступне ТО'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='parts_replaced',
            field=models.TextField(blank=True, verbose_name='Замінені деталі'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець'),
        ),
    ]
