# Generated by Django 4.2.28 on 2026-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0003_dronemodel_manufacturer_alter_dronetype_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
