# Generated by Django 4.2.28 on 2026-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0003_add_is_unusable_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavinstance',
            name='status',
            field=models.CharField(choices=[('inspection', 'На перевірці'), ('ready', 'Готовий'), ('repair', 'Ремонт'), ('deferred', 'Відкладено')], default='inspection', max_length=20, verbose_name='Статус'),
        ),
    ]
