# Generated by Django 4.2.28 on 2026-02-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0004_manufacturer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetype',
            name='has_guidance_system',
            field=models.BooleanField(default=False, verbose_name='Система донаведення'),
        ),
    ]
