# Generated by Django 4.2.28 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0005_migrate_old_uav_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavinstance',
            name='kit_status',
            field=models.CharField(choices=[('in_use', 'Використовується'), ('damaged', 'Пошкоджено'), ('disassembled', 'Розкомплектовано')], default='in_use', max_length=20, verbose_name='Комплектність'),
        ),
    ]
