# Generated by Django 4.2.28 on 2026-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0005_dronetype_has_guidance_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetype',
            name='control_frequency',
            field=models.CharField(blank=True, help_text='Наприклад: 868 МГц, 915 МГц, 2.4 ГГц', max_length=100, verbose_name='Частота керування'),
        ),
        migrations.AddField(
            model_name='dronetype',
            name='video_frequency',
            field=models.CharField(blank=True, help_text='Наприклад: 1.2 ГГц, 2.4 ГГц, 5.8 ГГц', max_length=100, verbose_name='Частота відео'),
        ),
    ]
