# Generated by Django 4.2.28 on 2026-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0006_dronetype_control_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Частота',
                'verbose_name_plural': 'Частоти',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='control_frequency',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='video_frequency',
        ),
        migrations.AddField(
            model_name='dronetype',
            name='control_frequencies',
            field=models.ManyToManyField(blank=True, related_name='control_drone_types', to='equipment_accounting.frequency', verbose_name='Частоти керування'),
        ),
        migrations.AddField(
            model_name='dronetype',
            name='video_frequencies',
            field=models.ManyToManyField(blank=True, related_name='video_drone_types', to='equipment_accounting.frequency', verbose_name='Частоти відео'),
        ),
    ]
