# Generated by Django 4.2.28 on 2026-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0006_uavinstance_kit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uavinstance',
            name='kit_status',
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('in_use', 'Використовується'), ('damaged', 'Пошкоджено'), ('disassembled', 'Розкомплектовано')], default='in_use', max_length=20, verbose_name='Статус'),
        ),
    ]
