# Generated by Django 4.2.28 on 2026-02-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0007_frequency_remove_dronetype_control_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='name',
            new_name='value',
        ),
    ]
