# Generated by Django 4.2.28 on 2026-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0008_migrate_component_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavinstance',
            name='status',
            field=models.CharField(choices=[('ready', 'Готовий'), ('inspection', 'На перевірці'), ('repair', 'Ремонт'), ('deferred', 'Відкладено'), ('deleted', 'Видалено')], default='inspection', max_length=20, verbose_name='Статус'),
        ),
    ]
