# Generated by Django 4.2.28 on 2026-02-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0008_rename_frequency_name_to_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['value'], 'verbose_name': 'Частота', 'verbose_name_plural': 'Частоти'},
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='control_frequencies',
            field=models.ManyToManyField(blank=True, related_name='control_drone_types', to='equipment_accounting.frequency', verbose_name='Частота керування'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='video_frequencies',
            field=models.ManyToManyField(blank=True, related_name='video_drone_types', to='equipment_accounting.frequency', verbose_name='Частота відео'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='value',
            field=models.CharField(max_length=50, unique=True, verbose_name='Значення'),
        ),
    ]
