# Generated by Django 4.2.28 on 2026-02-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0009_add_deleted_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpvdronetype',
            name='is_unusable',
        ),
        migrations.RemoveField(
            model_name='opticaldronetype',
            name='is_unusable',
        ),
    ]
