# Generated by Django 4.2.28 on 2026-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0009_alter_frequency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetype',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва'),
        ),
    ]
