# Generated by Django 4.2.28 on 2026-02-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0010_dronetype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronetype',
            name='control_frequencies',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='video_frequencies',
        ),
        migrations.AddField(
            model_name='dronetype',
            name='control_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_drone_types', to='equipment_accounting.frequency', verbose_name='Частота керування'),
        ),
        migrations.AddField(
            model_name='dronetype',
            name='video_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_drone_types', to='equipment_accounting.frequency', verbose_name='Частота відео'),
        ),
    ]
