# Generated by Django 4.2.28 on 2026-02-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0010_remove_is_unusable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpvdronetype',
            name='control_frequencies',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_control', to='equipment_accounting.frequency', verbose_name='Частоти керування'),
        ),
        migrations.AddField(
            model_name='opticaldronetype',
            name='control_frequencies',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_control', to='equipment_accounting.frequency', verbose_name='Частоти керування'),
        ),
        migrations.AlterField(
            model_name='fpvdronetype',
            name='control_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_control_old', to='equipment_accounting.frequency', verbose_name='Частота керування'),
        ),
        migrations.AlterField(
            model_name='opticaldronetype',
            name='control_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_control_old', to='equipment_accounting.frequency', verbose_name='Частота керування'),
        ),
    ]
