# Generated by Django 4.2.28 on 2026-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0011_remove_dronetype_control_frequencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronetype',
            name='max_flight_time',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='max_payload',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='max_range',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='weight',
        ),
        migrations.AddField(
            model_name='dronetype',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
    ]
