# Generated by Django 4.2.28 on 2026-02-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0012_remove_dronetype_max_flight_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_types', to='equipment_accounting.dronecategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_types', to='equipment_accounting.manufacturer', verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_types', to='equipment_accounting.dronemodel', verbose_name='Модель'),
        ),
    ]
