# Generated by Django 4.2.28 on 2026-02-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0012_migrate_control_freq_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpvdronetype',
            name='control_frequency',
        ),
        migrations.RemoveField(
            model_name='opticaldronetype',
            name='control_frequency',
        ),
    ]
