# Generated by Django 4.2.28 on 2026-02-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0013_remove_control_frequency_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplate',
            name='drone_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronemodel', verbose_name='Тип дрона'),
        ),
    ]
