# Generated by Django 4.2.28 on 2026-02-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0014_videotemplate_drone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='powertemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='drone_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment_accounting.dronemodel', verbose_name='Тип дрона'),
        ),
    ]
