# Generated by Django 4.2.28 on 2026-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0017_remove_component_generic_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavinstance',
            name='status',
            field=models.CharField(choices=[('ready', 'Готовий'), ('inspection', 'На перевірці'), ('repair', 'Ремонт'), ('deferred', 'Відкладено'), ('given', 'Віддано'), ('deleted', 'Видалено')], default='inspection', max_length=20, verbose_name='Статус'),
        ),
    ]
