# Generated by Django 4.2.28 on 2026-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0018_add_given_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('in_use', 'Використовується'), ('damaged', 'Пошкоджено'), ('disassembled', 'Розкомплектовано'), ('given', 'Віддано')], default='in_use', max_length=20, verbose_name='Статус'),
        ),
    ]
