# Generated by Django 4.2.28 on 2026-02-22 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_accounting', '0020_fix_videotemplate_drone_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('location_type', models.CharField(choices=[('workshop', 'Майстерня'), ('manufacturer', 'Виробник'), ('brigade', 'Бригада'), ('dusha', 'Дюша'), ('position', 'Позиція')], max_length=20, verbose_name='Тип')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UAVMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('created', 'Надійшов'), ('given', 'Відданий'), ('repair', 'Ремонт'), ('returned', 'Повернуто'), ('transferred', 'Переміщено')], default='transferred', max_length=20, verbose_name='Причина')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='equipment_accounting.location', verbose_name='Звідки')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uav_movements', to=settings.AUTH_USER_MODEL, verbose_name='Хто переміщав')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='equipment_accounting.location', verbose_name='Куди')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='equipment_accounting.uavinstance', verbose_name='БПЛА')),
            ],
            options={
                'verbose_name': 'Переміщення БПЛА',
                'verbose_name_plural': 'Переміщення БПЛА',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uavinstance',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_uavs', to='equipment_accounting.location', verbose_name='Поточна локація'),
        ),
    ]
