# Generated by Django 4.2.28 on 2026-02-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0022_seed_locations_and_set_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Роль БПЛА',
                'verbose_name_plural': 'Ролі БПЛА',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='uavinstance',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='equipment_accounting.dronerole', verbose_name='Роль'),
        ),
    ]
