# Generated by Django 4.2.28 on 2026-02-23 05:37

from django.db import migrations


def set_default_role(apps, schema_editor):
    UAVInstance = apps.get_model('equipment_accounting', 'UAVInstance')
    DroneRole = apps.get_model('equipment_accounting', 'DroneRole')
    try:
        strike = DroneRole.objects.get(name='Ударні')
    except DroneRole.DoesNotExist:
        return
    UAVInstance.objects.filter(role__isnull=True).update(role=strike)


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0023_add_drone_role'),
    ]

    operations = [
        migrations.RunPython(set_default_role, migrations.RunPython.noop),
    ]
