# Generated by Django 4.2.28 on 2026-02-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0024_set_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavinstance',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Мотогодини'),
        ),
        migrations.AddField(
            model_name='uavinstance',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='uavinstance',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='equipment_accounting.dronerole', verbose_name='Призначення'),
        ),
    ]
