# Generated by Django 4.2.28 on 2026-02-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0025_add_serial_and_flight_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uavinstance',
            name='flight_hours',
        ),
        migrations.RemoveField(
            model_name='uavinstance',
            name='serial_number',
        ),
    ]
