# Generated by Django 4.2.28 on 2026-03-03 11:32

from django.db import migrations, models
import django.db.models.deletion
import equipment_accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0026_remove_serial_and_flight_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=equipment_accounting.models._uav_photo_path, verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='equipment_accounting.uavinstance', verbose_name='БПЛА')),
            ],
            options={
                'verbose_name': 'Фото БПЛА',
                'verbose_name_plural': 'Фото БПЛА',
                'ordering': ['created_at'],
            },
        ),
    ]
