# Generated by Django 4.2.28 on 2026-03-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_accounting', '0027_add_uav_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavinstance',
            name='pending_to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_arrivals', to='equipment_accounting.location', verbose_name='Очікувана локація'),
        ),
        migrations.AddField(
            model_name='uavmovement',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено'),
        ),
        migrations.AddField(
            model_name='uavmovement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_uav_movements', to=settings.AUTH_USER_MODEL, verbose_name='Підтвердив'),
        ),
        migrations.AddField(
            model_name='uavmovement',
            name='pre_transit_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус до переміщення'),
        ),
        migrations.AlterField(
            model_name='uavinstance',
            name='status',
            field=models.CharField(choices=[('ready', 'Готовий'), ('inspection', 'На перевірці'), ('repair', 'Ремонт'), ('deferred', 'Відкладено'), ('transit', 'В дорозі'), ('given', 'Віддано'), ('deleted', 'Видалено')], default='inspection', max_length=20, verbose_name='Статус'),
        ),
    ]
