# Generated by Django 4.2.28 on 2026-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0028_transit_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavinstance',
            name='position_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва позиції'),
        ),
    ]
