# Generated by Django 4.2.28 on 2026-03-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0029_add_uavinstance_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Позиція',
                'verbose_name_plural': 'Позиції',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='uavinstance',
            name='position_name',
        ),
        migrations.AddField(
            model_name='uavinstance',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='equipment_accounting.position', verbose_name='Позиція'),
        ),
    ]
