# Generated by Django 4.2.28 on 2026-03-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0031_seed_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
    ]
