# Generated by Django 4.2.28 on 2026-03-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0032_remove_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpvdronetype',
            name='video_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fpv_video', to='equipment_accounting.frequency', verbose_name='Частота відео'),
        ),
    ]
