# Generated by Django 4.2.28 on 2026-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0033_fpvdronetype_video_frequency_nullable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uavinstance',
            index=models.Index(fields=['status'], name='uav_status_idx'),
        ),
        migrations.AddIndex(
            model_name='uavinstance',
            index=models.Index(fields=['created_at'], name='uav_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='uavinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='uav_gfk_idx'),
        ),
        migrations.AddIndex(
            model_name='uavinstance',
            index=models.Index(fields=['status', 'content_type', 'object_id'], name='uav_status_gfk_idx'),
        ),
    ]
