# Generated by Django 4.2.28 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0034_uavinstance_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['assigned_to_uav', 'kind'], name='component_uav_kind_idx'),
        ),
    ]
