# Generated by Django 4.2.28 on 2026-03-08 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_accounting', '0036_add_can_repair_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Від')),
                ('to_status', models.CharField(max_length=20, verbose_name='До')),
                ('drone_type_label', models.CharField(blank=True, max_length=200, verbose_name='Тип БПЛА')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uav_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='equipment_accounting.uavinstance', verbose_name='БПЛА')),
            ],
            options={
                'verbose_name': 'Зміна статусу БПЛА',
                'verbose_name_plural': 'Зміни статусів БПЛА',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='statuslog_created_idx'), models.Index(fields=['uav'], name='statuslog_uav_idx')],
            },
        ),
    ]
