# Generated by Django 4.2.28 on 2026-03-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0037_add_uavstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavstatuslog',
            name='from_status',
            field=models.CharField(blank=True, choices=[('ready', 'Готовий'), ('inspection', 'На перевірці'), ('repair', 'Ремонт'), ('deferred', 'Відкладено'), ('transit', 'В дорозі'), ('given', 'Віддано'), ('deleted', 'Видалено')], max_length=20, verbose_name='Від'),
        ),
        migrations.AlterField(
            model_name='uavstatuslog',
            name='to_status',
            field=models.CharField(choices=[('ready', 'Готовий'), ('inspection', 'На перевірці'), ('repair', 'Ремонт'), ('deferred', 'Відкладено'), ('transit', 'В дорозі'), ('given', 'Віддано'), ('deleted', 'Видалено')], max_length=20, verbose_name='До'),
        ),
    ]
