# Generated by Django 4.2.28 on 2026-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0038_add_choices_to_statuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpvdronetype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drone_types/', verbose_name='Фото зовнішнього вигляду'),
        ),
        migrations.AddField(
            model_name='opticaldronetype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drone_types/', verbose_name='Фото зовнішнього вигляду'),
        ),
    ]
