# Generated by Django 4.2.28 on 2026-03-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0040_migrate_role_to_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavinstance',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='equipment_accounting.dronepurpose', verbose_name='Призначення'),
        ),
    ]
