# Generated by Django 4.2.28 on 2026-03-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_accounting', '0042_uavmovement_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='component',
            name='component_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='uavmovement',
            name='uavmove_uav_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='uavmovement',
            name='uavmove_to_loc_idx',
        ),
    ]
